/**
 * Executive summary text.
 *
 * Generated by deterministic rules over the precomputed statistics — no model,
 * no runtime API call. The same data always produces the same words, which is
 * what makes it safe to put in front of an audience that will quote it. The UI
 * labels it as rule-generated for exactly that reason.
 */

import type { Manifest, ManifestEntry } from './manifest';
import type { Polarity } from '../config/indicators';
import { formatDisplay, formatPeriod } from './format';

export interface CommentaryBlock {
  title: string;
  text: string;
}

/** Read a direction through the lens of whether up is good for this series. */
function judge(
  direction: 'rising' | 'falling' | 'flat',
  polarity: Polarity,
): 'improving' | 'deteriorating' | 'stable' {
  if (direction === 'flat' || polarity === 'neutral') {
    return direction === 'flat' ? 'stable' : 'stable';
  }
  const good = polarity === 'higher-is-better' ? 'rising' : 'falling';
  return direction === good ? 'improving' : 'deteriorating';
}

function movement(direction: 'rising' | 'falling' | 'flat'): string {
  switch (direction) {
    case 'rising':
      return 'has been rising';
    case 'falling':
      return 'has been easing';
    default:
      return 'has been broadly flat';
  }
}

/** "0.4 points higher than a year ago", or null when there is no comparison. */
function versusYearAgo(entry: ManifestEntry): string | null {
  const { changeYear } = entry.stats;
  if (changeYear == null) return null;

  const magnitude = Math.abs(changeYear);
  const unit = entry.indicator.transform === 'yoy' ? 'points' : 'points';

  if (magnitude < 0.05) return 'little changed from a year ago';
  return `${formatDisplay(magnitude, entry.indicator, { bare: true })} ${unit} ${
    changeYear > 0 ? 'higher' : 'lower'
  } than a year ago`;
}

function ordinal(n: number): string {
  const v = Math.round(n);
  const suffix = v % 100 >= 11 && v % 100 <= 13 ? 'th' : ['th', 'st', 'nd', 'rd'][v % 10] ?? 'th';
  return `${v}${suffix}`;
}

export function generateCommentary(manifest: Manifest): CommentaryBlock[] {
  const e = (id: string): ManifestEntry | undefined => manifest.entries[id];
  const blocks: CommentaryBlock[] = [];
  const say = (title: string, sentences: (string | null)[]) => {
    const text = sentences.filter(Boolean).join(' ');
    if (text) blocks.push({ title, text });
  };

  // ── Inflation ────────────────────────────────────────────────────────
  {
    const corePce = e('PCEPILFE');
    const coreCpi = e('CPILFESL');
    const sentences: (string | null)[] = [];

    if (corePce) {
      const v = corePce.stats.latest;
      const gap = v - 2;
      sentences.push(
        `Core PCE inflation — the measure the Federal Reserve's 2% target is defined against — ` +
          `stands at ${formatDisplay(v, corePce.indicator)} year-on-year as of ` +
          `${formatPeriod(corePce.stats.latestDate, corePce.indicator.frequency)}, ` +
          `${Math.abs(gap) < 0.1 ? 'essentially at target' : `${Math.abs(gap).toFixed(1)} points ${gap > 0 ? 'above' : 'below'} target`}.`,
      );
      sentences.push(`It ${movement(corePce.stats.direction)} in recent months.`);
    }

    if (coreCpi) {
      const alt = versusYearAgo(coreCpi);
      sentences.push(
        `Core CPI reads ${formatDisplay(coreCpi.stats.latest, coreCpi.indicator)}${alt ? `, ${alt}` : ''}.`,
      );
    }

    const shelter = e('CUSR0000SAH1');
    if (shelter) {
      sentences.push(
        `Shelter costs, roughly a third of the CPI basket and the slowest-moving component, ` +
          `are running at ${formatDisplay(shelter.stats.latest, shelter.indicator)}.`,
      );
    }

    say('Inflation', sentences);
  }

  // ── Labour market ────────────────────────────────────────────────────
  {
    const unrate = e('UNRATE');
    const payems = e('PAYEMS');
    const openings = e('JTSJOL');
    const sentences: (string | null)[] = [];

    if (unrate) {
      const pct = unrate.stats.percentile10y;
      sentences.push(
        `Unemployment is ${formatDisplay(unrate.stats.latest, unrate.indicator)}` +
          (pct != null ? `, the ${ordinal(pct)} percentile of the past decade` : '') +
          `, and ${judge(unrate.stats.direction, unrate.indicator.polarity)}.`,
      );
    }

    if (payems) {
      const v = payems.stats.latest;
      sentences.push(
        v < 0
          ? `The economy shed ${formatDisplay(Math.abs(v), payems.indicator)} jobs in the latest month.`
          : `Employers added ${formatDisplay(v, payems.indicator)} jobs in the latest month.`,
      );
    }

    if (openings) {
      sentences.push(
        `Job openings stand at ${formatDisplay(openings.stats.latest, openings.indicator)}, ` +
          `a leading signal for hiring demand, and the trend ${movement(openings.stats.direction)}.`,
      );
    }

    say('Labour Market', sentences);
  }

  // ── Growth ───────────────────────────────────────────────────────────
  {
    const gdp = e('A191RL1Q225SBEA');
    const indpro = e('INDPRO');
    const sentences: (string | null)[] = [];

    if (gdp) {
      const v = gdp.stats.latest;
      sentences.push(
        `Real GDP ${v < 0 ? 'contracted' : 'grew'} at an annualised ` +
          `${formatDisplay(Math.abs(v), gdp.indicator)} in ` +
          `${formatPeriod(gdp.stats.latestDate, gdp.indicator.frequency)}.`,
      );
    }

    const nowcast = e('GDPNOW');
    if (nowcast) {
      sentences.push(
        `The Atlanta Fed's GDPNow model currently tracks the present quarter at ` +
          `${formatDisplay(nowcast.stats.latest, nowcast.indicator)}.`,
      );
    }

    if (indpro) {
      sentences.push(
        `Industrial production is ${formatDisplay(indpro.stats.latest, indpro.indicator)} ` +
          `against a year earlier.`,
      );
    }

    say('Growth', sentences);
  }

  // ── Policy and rates ─────────────────────────────────────────────────
  {
    const ff = e('FEDFUNDS');
    const curve = e('T10Y2Y');
    const mortgage = e('MORTGAGE30US');
    const sentences: (string | null)[] = [];

    if (ff) {
      sentences.push(
        `The federal funds rate is ${formatDisplay(ff.stats.latest, ff.indicator)}` +
          (ff.stats.changeYear != null && Math.abs(ff.stats.changeYear) >= 0.1
            ? `, ${Math.abs(ff.stats.changeYear).toFixed(2)} points ${ff.stats.changeYear > 0 ? 'higher' : 'lower'} than a year ago`
            : '') +
          '.',
      );
    }

    if (curve) {
      const v = curve.stats.latest;
      sentences.push(
        v < 0
          ? `The 10Y–2Y curve is inverted at ${formatDisplay(v, curve.indicator)}, a configuration that has preceded every US recession since 1955.`
          : `The 10Y–2Y curve is positively sloped at ${formatDisplay(v, curve.indicator)}.`,
      );
    }

    if (mortgage) {
      sentences.push(
        `Thirty-year mortgage rates are ${formatDisplay(mortgage.stats.latest, mortgage.indicator)}.`,
      );
    }

    say('Monetary Policy & Rates', sentences);
  }

  // ── Consumer ─────────────────────────────────────────────────────────
  {
    const sentiment = e('UMCSENT');
    const retail = e('RRSFS');
    const income = e('DSPIC96');
    const sentences: (string | null)[] = [];

    if (sentiment) {
      const pct = sentiment.stats.percentile10y;
      sentences.push(
        `Consumer sentiment reads ${formatDisplay(sentiment.stats.latest, sentiment.indicator)}` +
          (pct != null ? `, the ${ordinal(pct)} percentile of the past ten years` : '') +
          `, and ${movement(sentiment.stats.direction)}.`,
      );
    }

    if (retail) {
      sentences.push(
        `Inflation-adjusted retail sales are ${formatDisplay(retail.stats.latest, retail.indicator)} ` +
          `on a year earlier.`,
      );
    }

    if (income) {
      sentences.push(
        `Real disposable income is ${formatDisplay(income.stats.latest, income.indicator)} year-on-year, ` +
          `which is what determines whether spending can be sustained without drawing on savings or credit.`,
      );
    }

    say('Consumer', sentences);
  }

  // ── Dollar and markets ───────────────────────────────────────────────
  {
    const dollar = e('DTWEXBGS');
    const sp = e('SP500');
    const oil = e('WTISPLC');
    const sentences: (string | null)[] = [];

    if (dollar) {
      const chg = dollar.stats.changeYear;
      sentences.push(
        `The broad trade-weighted dollar index stands at ${formatDisplay(dollar.stats.latest, dollar.indicator)}` +
          (chg != null && Math.abs(chg) > 0.5
            ? `, ${chg > 0 ? 'stronger' : 'weaker'} than a year ago`
            : ', little changed on the year') +
          '.',
      );
    }

    if (sp) {
      const chg = sp.stats.changeYear;
      if (chg != null && sp.stats.latest - chg !== 0) {
        const pct = (chg / (sp.stats.latest - chg)) * 100;
        sentences.push(
          `The S&P 500 is ${Math.abs(pct).toFixed(1)}% ${pct >= 0 ? 'higher' : 'lower'} over the past twelve months.`,
        );
      }
    }

    if (oil) {
      sentences.push(`WTI crude is ${formatDisplay(oil.stats.latest, oil.indicator)} per barrel.`);
    }

    say('Dollar, Markets & Commodities', sentences);
  }

  return blocks;
}
