import { useMemo } from 'react';

import type { Manifest } from '../lib/manifest';
import type { Category } from '../config/indicators';
import { HEADLINE_INDICATORS } from '../config/indicators';
import { assessRegime } from '../lib/regime';
import { generateCommentary } from '../lib/commentary';
import { formatDate } from '../lib/format';
import { StatTile } from '../components/StatTile';
import { RegimeScorecard } from '../components/RegimeScorecard';

interface Props {
  manifest: Manifest;
  onNavigate: (category: Category) => void;
}

export function ExecutiveSummary({ manifest, onNavigate }: Props) {
  const assessment = useMemo(() => assessRegime(manifest), [manifest]);
  const commentary = useMemo(() => generateCommentary(manifest), [manifest]);

  const tiles = HEADLINE_INDICATORS.map((i) => manifest.entries[i.id]).filter(Boolean);

  return (
    <div className="space-y-6">
      <section>
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h2 className="text-base font-semibold text-ink">Headline Indicators</h2>
          <p className="text-xs text-ink-muted">
            Data through {formatDate(manifest.dataThrough)}
          </p>
        </div>
        <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {tiles.map((entry) => (
            <StatTile
              key={entry.indicator.id}
              entry={entry}
              onSelect={(c) => onNavigate(c as Category)}
            />
          ))}
        </div>
      </section>

      <RegimeScorecard assessment={assessment} />

      <section className="rounded-xl border border-edge bg-surface p-5 shadow-[var(--shadow-card)]">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <h2 className="text-sm font-semibold text-ink">State of the Economy</h2>
          <span className="rounded-full border border-edge px-2 py-0.5 text-[11px] text-ink-muted">
            Rule-generated from the latest data
          </span>
        </div>

        <div className="mt-4 grid grid-cols-1 gap-x-8 gap-y-5 md:grid-cols-2">
          {commentary.map((block) => (
            <article key={block.title}>
              <h3 className="text-xs font-semibold uppercase tracking-wide text-ink-muted">
                {block.title}
              </h3>
              <p className="mt-1.5 text-sm leading-relaxed text-ink-secondary">{block.text}</p>
            </article>
          ))}
        </div>

        <p className="mt-5 border-t border-edge pt-3 text-[11px] leading-relaxed text-ink-muted">
          This summary is produced by deterministic rules applied to the published
          figures — thresholds, directions and percentile ranks. It is not a
          forecast, and it is not generated by a language model. The same data
          always yields the same wording.
        </p>
      </section>
    </div>
  );
}
